manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: thilojaeggi
      url-base: https://github.com/thilojaeggi
  projects:
    - name: zmk
      remote: thilojaeggi
      revision: display/bongo-cat-widget
      import: app/west.yml
  self:
    path: config