manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: okke-formsma
      url-base: https://github.com/okke-formsma
  projects:
    - name: zmk
      remote: petejohanson
      revision: display/bongo-cat-widget
      import: app/west.yml
  self:
    path: config